console.log("Hii in the start")

try{
let user =undefined
console.log(user.name)
}catch(err)
{
    console.log("It is an error")
}